include: package:flutter_lints/flutter.yaml

# RiverpodのカスタムLint
analyzer:
  plugins:
    - custom_lint

linter:
  rules:
    # 絶対パスでimportさせる（相対パスを禁止）
    always_use_package_imports: true
    # カンマを揃える（これがないと閉じ括弧が連続してしまう）
    require_trailing_commas: true
