name: vuuum_app
description: vuuum_app
publish_to: "none"

version: 0.2.9+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: any
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  video_player: ^2.6.1
  simple_logger: ^1.9.0+2
  share_plus: ^7.0.0
  flutter_secure_storage: ^8.0.0
  package_info_plus: ^4.0.0
  pinput: ^2.2.31
  flutter_native_splash: ^2.2.19
  fluttertoast: ^8.2.1
  firebase_core: ^2.12.0
  firebase_messaging: ^14.6.0
  firebase_analytics: ^10.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  custom_lint: ^0.4.0
  riverpod_lint: ^1.3.2
  build_runner: ^2.4.4
  riverpod_generator: ^2.2.3
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true

  # アセット
  assets:
    # アイコン
    - assets/icon/logo.png
    # 画像（ダミー）
    - assets/images/artist.png
    # 動画（ダミー）
    - assets/videos/purple.mp4
    - assets/videos/burande.mp4
    - assets/videos/ff.mp4
    - assets/videos/hakuchumu.mp4
    - assets/videos/hoshimati.mp4
    - assets/videos/alia.mp4
    - assets/videos/nemurenai.mp4
